### ISSUE TITLE
Add/Setup Watcharr

### ISSUE THREAD

**Issue by D1noD3v** [D1noD3v/zagreus-server-config#4]
Watcharr is a open source, self-hostable watched list for all your content (movies, tv series, anime, games) with user authentication, modern and clean UI and a very simple setup. 

Docker config below, change to desired directories or ports.

```yaml
services:
  watcharr:
    # The :latest tag is used for simplicity, it is recommended
    # to use an actual version, then when updating check the releases for changelogs.
    image: ghcr.io/sbondco/watcharr:latest
    container_name: watcharr
    ports:
      - 3080:3080
    volumes:
      # Contains all of watcharr data (database & cache)
      - ./data:/data
    restart: unless-stopped
```
