### ISSUE TITLE
Add/Setup Vaultwarden

### ISSUE THREAD

**Issue by D1noD3v** [D1noD3v/zagreus-server-config#5]
Unofficial Bitwarden compatible server written in Rust, formerly known as bitwarden_rs 

Don't use this by itself, use the [3-2-1 backup](https://www.backblaze.com/blog/the-3-2-1-backup-strategy/) method in case data is lost locally or remotely.

```yaml
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.domain.tld"
    volumes:
      - ./vw-data/:/data/
    ports:
      - 80:80
```
