### ISSUE TITLE
Add/Setup SearXNG

### ISSUE THREAD

**Issue by D1noD3v** [D1noD3v/zagreus-server-config#6]
SearXNG is a free internet metasearch engine which aggregates results from up to 215 [search services](https://docs.searxng.org/user/configured_engines.html#configured-engines). Users are neither tracked nor profiled. Additionally, SearXNG can be used over Tor for online anonymity.

Might be a hassel to setup? But we shall see.

YouTube Video that inspired: [https://youtu.be/SlqGDoXPazY](https://youtu.be/SlqGDoXPazY)

```yaml
services:
    searxng:
        image: searxng/searxng
        environment:
            - INSTANCE_NAME=my-instance
            - 'BASE_URL=http://localhost:$PORT/'
        volumes:
            - '${PWD}/searxng:/etc/searxng'
        ports:
            - '${PORT}:8080'
```
